### ISSUE TITLE
500 Internal Error

### ISSUE THREAD

**Issue by NicosHere** [Vuinea/StudentCheck#5]
Whenever I try to login I receive a 500 error. Unsure if it's supposed to be working yet but I'm logging in through SMUSD.

**Comment by Vuinea** [comment]
Did you pick the schools from the dropdown or did you just type it in yourself, because you need to select the county from the dropdown menu. If you did, then this is obviously my fault so I apologize and will try and fix it as soon as possible

**Comment by Vuinea** [comment]
Ok I will take a look and try to fix it. Sorry for the inconvenience.

**Comment by Vuinea** [comment]
Just wondering, are you running the code on your local machine or are you visiting the website? if you are running it on your local machine then go to the __init__.py file and change the SECRET_KEY to something different ("dev" is pretty common). But if you are running it on the website, then I can change the website to development mode, which will display the exact error.

**Comment by NicosHere** [comment]
Visiting Site

**Comment by Vuinea** [comment]
Ok, I made it a development server. Could you try to login again and then copy and paste the whole error page here please (cutting out your credentials)?

**Comment by Vuinea** [comment]
Thank you

**Comment by Vuinea** [comment]
Ok try to login now.

**Comment by NicosHere** [comment]
TypeError
TypeError: string indices must be integers

Traceback (most recent call last)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/home/runner/studentcheck/app/sv.py", line 78, in index
prediction = grade_prediction(user)
File "/home/runner/studentcheck/app/utils.py", line 105, in grade_prediction
assignments = get_weighted_assignments(user)
File "/home/runner/studentcheck/app/utils.py", line 89, in get_weighted_assignments
assignments = get_assignments(user)
File "/home/runner/studentcheck/app/utils.py", line 64, in get_assignments
if isinstance(a["Assignments"], list):
TypeError: string indices must be integers
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by Vuinea** [comment]
Sorry about this, can you try to login again?

**Comment by NicosHere** [comment]
TypeError
TypeError: string indices must be integers

Traceback (most recent call last)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/home/runner/studentcheck/app/sv.py", line 78, in index
prediction = grade_prediction(user)
File "/home/runner/studentcheck/app/utils.py", line 100, in grade_prediction
assignments = get_weighted_assignments(user)
File "/home/runner/studentcheck/app/utils.py", line 84, in get_weighted_assignments
assignments = get_assignments(user)[0]
File "/home/runner/studentcheck/app/utils.py", line 66, in get_assignments
course_assignments.append(a["Assignments"]["Assignment"])
TypeError: string indices must be integers
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by Vuinea** [comment]
ok try it now

**Comment by NicosHere** [comment]
TypeError
TypeError: string indices must be integers

Traceback (most recent call last)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/home/runner/studentcheck/app/sv.py", line 78, in index
prediction = grade_prediction(user)
File "/home/runner/studentcheck/app/utils.py", line 104, in grade_prediction
assignments = get_weighted_assignments(user)
File "/home/runner/studentcheck/app/utils.py", line 88, in get_weighted_assignments
assignments = get_assignments(user)[0]
File "/home/runner/studentcheck/app/utils.py", line 65, in get_assignments
if isinstance(a["Assignments"], list):
TypeError: string indices must be integers
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by Vuinea** [comment]
ok I think it's fixed now, but at this point I don't know

**Comment by NicosHere** [comment]
TypeError: string indices must be integers

Traceback (most recent call last)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/home/runner/studentcheck/app/sv.py", line 78, in index
prediction = grade_prediction(user)
File "/home/runner/studentcheck/app/utils.py", line 103, in grade_prediction
assignments = get_weighted_assignments(user)
File "/home/runner/studentcheck/app/utils.py", line 94, in get_weighted_assignments
if "not for grading" not in a["@Notes"].lower():
TypeError: string indices must be integers
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by Vuinea** [comment]
ok I tried to fix it again

**Comment by NicosHere** [comment]
Site isn't working.

**Comment by Vuinea** [comment]
ok, could you tell me the error please?

**Comment by Vuinea** [comment]
Sorry about that, it's running again.

**Comment by NicosHere** [comment]
TypeError
TypeError: string indices must be integers

Traceback (most recent call last)
File "/home/runner/studentcheck/app/utils.py", line 95, in get_weighted_assignments
if "not for grading" not in a["@Notes"].lower():
During handling of the above exception, another exception occurred:
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2091, in __call__
return self.wsgi_app(environ, start_response)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2076, in wsgi_app
response = self.handle_exception(e)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
response = self.full_dispatch_request()
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
rv = self.dispatch_request()
File "/opt/virtualenvs/python3/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
File "/home/runner/studentcheck/app/sv.py", line 78, in index
prediction = grade_prediction(user)
File "/home/runner/studentcheck/app/utils.py", line 108, in grade_prediction
assignments = get_weighted_assignments(user)
File "/home/runner/studentcheck/app/utils.py", line 99, in get_weighted_assignments
if "not for grading" not in new_a["@Notes"].lower():
TypeError: string indices must be integers
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object

**Comment by Vuinea** [comment]
Sorry Nico. As you can probably guess from the stack traces, the functions return different datatypes for you and me. I can't seem to figure out when it is a list or OrderedDict. If you want you can fork/clone the repository and then try and fix it for your county. My apologies for wasting your time,

**Comment by Vuinea** [comment]
Ok, this time it should work.

**Comment by NicosHere** [comment]
Based on what I'm seeing, it looks like the issue is on of my teachers made an assignment "Not for grading" which means it appears in the gradebook but doesn't affect the grade. This is only on one assignment and none of my teachers have done it before - hopefully this helps fix it. I'm fairly certain the databases should work in the same way.

`Traceback (most recent call last)
File "/home/runner/studentcheck/app/utils.py", line 95, in get_weighted_assignments
        lesson_grades_assignments = []
        if assignments[lesson_name] != "N/A":
            for i in assignments[lesson_name]:
                    for a in i:
                      try:
                        if "not for grading" not in a["@Notes"].lower():
                            lesson_grades_assignments.append(a)
                      except TypeError:
                        for new_a in a:
                          if "not for grading" not in new_a[0]["@Notes"].lower():
                            lesson_grades_assignments.append(new_a)`

**Comment by Vuinea** [comment]
Ok, I think I got it now. Thank you for your feedback. We'll see if it works
